### ISSUE TITLE
Pasame por email los datos de tu dominio

### ISSUE THREAD

**Issue by mauleyzaola** [lextes/lextes.github.io#3]
Necesito:
url
username
password

De esta forma puedo ir modificando los dns para que en lugar de apuntar a tu hosting actual, lo hagan al nuevo.

**Comment by lextes** [comment]
url: http://lextes.tecnificarte.net/wordpress/
username: lextes
pasword: lextes1708

Que padrisimo esta lo que me mandaste de biblioteca para disenadores y lo
de organizar tus tiempos, mil gracias estan bien chingones.

2016-02-12 17:38 GMT-05:00 Mauricio Leyzaola <notifications@github.com>:

**Comment by mauleyzaola** [comment]
Me alegro que te hayan servido. He aprendido a conseguir material de
calidad sin desgastar casi tiempo compa.

**Comment by mauleyzaola** [comment]
La url que me referia es donde compraste tu dominio, la del sitio ya la tenia gracias. Pasamela por email please.

**Comment by lextes** [comment]
http://hosting-mexico.net/

2016-02-12 18:56 GMT-05:00 Mauricio Leyzaola <notifications@github.com>:

**Comment by mauleyzaola** [comment]
Para la otra, insisto compa, involucrame te saldra mas barato y de mejor
calidad. En este simple ejemplo, son $500 de diferencia

[image: Inline image 1]

[image: Inline image 2]

**Comment by mauleyzaola** [comment]
@lextes Elimine los mensajes con contenido confidencial de aqui. Todo esta en gmail compa.

**Comment by mauleyzaola** [comment]
@lextes Que onda loco, no has hecho nada de esto. Estas batallando con algo especial?

**Comment by lextes** [comment]
Si, con la puta conexion: crear el keygen fue muy simple gracias, pero no
logro conectarme, he usado los pasos

echo "# lextes.github.io" >> README.md

git init

git add README.md

git commit -m "first commit"

git remote add origin git@github.com:lextes/lextes.github.io.git

git push -u origin master

Pero me marca error "fatal: remote origin already exists."

EStoy muy atorado en esto

2016-02-16 21:08 GMT-05:00 Mauricio Leyzaola notifications@github.com:

**Comment by mauleyzaola** [comment]
Compa, intenta responder por aqui, en lugar de hacer reply desde tu gmail, asi aparece menos basura en los comentarios.

Todos esos pasos que pones arriba son cuando tienes un repo nuevo, vacio. En tu caso ya tienes un repo, lo unico que debes hacer es un `git clone git@github.com:lextes/lextes.github.io.git` desde tu compu.

Que paso con ese curso de Github? :smile:

**Comment by lextes** [comment]
https://mx.m.godaddy.com/
