### ISSUE TITLE
Pagina index.html no debe tener ligas rotas

### ISSUE THREAD

**Issue by mauleyzaola** [lextes/lextes.github.io#5]

**Comment by lextes** [comment]
![image](https://cloud.githubusercontent.com/assets/16492764/13273827/668ce58c-da74-11e5-9d1b-b80d123df74a.png)

**Comment by mauleyzaola** [comment]
![image](https://cloud.githubusercontent.com/assets/1648558/13273846/2384076e-da6c-11e5-87e9-4d6545de5a36.png)
